const { sql, poolPromise } = require('../config/db');

class Conversation {
  /**
   * Retrieves the most recent chat history for a user and formats it in chronological order.
   * @param {string} userId - The unique identifier of the user
   * @param {number} limit - Maximum number of message pairs to retrieve
   * @returns {Promise<Array>} Chronological list of message pairs
   */
  static async getHistoryByUserId(userId, limit = 20) {
    const pool = await poolPromise;
    const request = pool.request();
    request.input('user_id', sql.UniqueIdentifier, userId);
    request.input('limit', sql.Int, limit);

    // Retrieve the most recent pairs first, ordered by created_at DESC to get the latest ones
    const result = await request.query(`
      SELECT TOP (@limit) id, user_id, user_message, ai_response, created_at
      FROM conversation_history
      WHERE user_id = @user_id AND is_deleted = 0
      ORDER BY created_at DESC
    `);

    // Reverse the array to put it in chronological order (oldest to newest)
    return result.recordset.reverse();
  }

  /**
   * Saves a new user message and the corresponding AI reply.
   * @param {string} userId - The unique identifier of the user
   * @param {string} userMessage - The message sent by the user
   * @param {string} aiResponse - The response generated by the AI
   * @returns {Promise<Object>} The created database record
   */
  static async create(userId, userMessage, aiResponse) {
    const pool = await poolPromise;
    const request = pool.request();
    request.input('user_id', sql.UniqueIdentifier, userId);
    request.input('user_message', sql.NVarChar(sql.MAX), userMessage);
    request.input('ai_response', sql.NVarChar(sql.MAX), aiResponse);

    const query = `
      INSERT INTO conversation_history (id, user_id, user_message, ai_response, is_deleted)
      OUTPUT INSERTED.*
      VALUES (NEWID(), @user_id, @user_message, @ai_response, 0)
    `;

    const result = await request.query(query);
    return result.recordset[0];
  }

  /**
   * Soft-deletes all conversation history for a specific user.
   * @param {string} userId - The unique identifier of the user
   * @returns {Promise<boolean>} True if records were deleted, false otherwise
   */
  static async clearHistoryByUserId(userId) {
    const pool = await poolPromise;
    const request = pool.request();
    request.input('user_id', sql.UniqueIdentifier, userId);

    const result = await request.query(`
      UPDATE conversation_history
      SET is_deleted = 1
      WHERE user_id = @user_id AND is_deleted = 0
    `);

    return result.rowsAffected[0] > 0;
  }
}

module.exports = Conversation;
