const { poolPromise } = require('../config/db');

class Conversation {
  /**
   * Retrieves the most recent chat history for a user and formats it in chronological order.
   * @param {string} userId - The unique identifier of the user
   * @param {number} limit - Maximum number of message pairs to retrieve
   * @returns {Promise<Array>} Chronological list of message pairs
   */
  static async getHistoryByUserId(userId, limit = 20) {
    const pool = await poolPromise;

    // Retrieve the most recent pairs first, ordered by created_at DESC to get the latest ones
    const result = await pool.query(
      `SELECT id, user_id, user_message, ai_response, created_at
       FROM conversation_history
       WHERE user_id = $1 AND is_deleted = false
       ORDER BY created_at DESC
       LIMIT $2`,
      [userId, limit]
    );

    // Reverse the array to put it in chronological order (oldest to newest)
    return result.rows.reverse();
  }

  /**
   * Saves a new user message and the corresponding AI reply.
   * @param {string} userId - The unique identifier of the user
   * @param {string} userMessage - The message sent by the user
   * @param {string} aiResponse - The response generated by the AI
   * @returns {Promise<Object>} The created database record
   */
  static async create(userId, userMessage, aiResponse) {
    const pool = await poolPromise;
    const result = await pool.query(
      `INSERT INTO conversation_history (id, user_id, user_message, ai_response, is_deleted)
       VALUES (gen_random_uuid(), $1, $2, $3, false)
       RETURNING *`,
      [userId, userMessage, aiResponse]
    );
    return result.rows[0];
  }

  /**
   * Soft-deletes all conversation history for a specific user.
   * @param {string} userId - The unique identifier of the user
   * @returns {Promise<boolean>} True if records were deleted, false otherwise
   */
  static async clearHistoryByUserId(userId) {
    const pool = await poolPromise;
    const result = await pool.query(
      `UPDATE conversation_history
       SET is_deleted = true
       WHERE user_id = $1 AND is_deleted = false`,
      [userId]
    );
    return result.rowCount > 0;
  }
}

module.exports = Conversation;
