import type { OrderRow } from './types'

/** Initial lab orders (synced across Order management, Collection routing, Results). */
export const INITIAL_ORDERS: OrderRow[] = [
  {
    orderId: 'LAB1021',
    patientName: 'John Doe',
    patientPhone: '+95 9 123 456 789',
    testType: 'Blood Test',
    orderDate: '2026-04-24',
    status: 'testing',
    paymentStatus: 'paid',
    technician: 'Kyaw Kyaw',
    source: 'patient_app',
    patientAddress: 'No. 12 Demo Street, Kamayut Township, Yangon',
    amountMmk: 85_000,
    collectionTime: '2026-04-24T10:00',
    collectingPerson: 'Ko Htoo',
    labRunningCompleteAt: '2026-04-24T18:00',
    reportOutTime: '2026-04-25T09:00',
    resultPdfFileName: null,
    aiReviewPassed: null,
    aiReviewNotes: null,
    resultSentToUserApp: false,
  },
  {
    orderId: 'LAB1022',
    patientName: 'Mary Su',
    patientPhone: '+95 9 200 300 400',
    testType: 'Diabetes Test',
    orderDate: '2026-04-23',
    status: 'collection',
    paymentStatus: 'partial',
    technician: undefined,
    source: 'patient_app',
    patientAddress: '45 Bogyoke Road, Sanchaung, Yangon',
    amountMmk: 120_000,
    collectionTime: '2026-04-26T09:30',
    collectingPerson: 'Ma Thin',
    labRunningCompleteAt: '2026-04-26T20:00',
    reportOutTime: '2026-04-27T10:00',
    resultPdfFileName: null,
    aiReviewPassed: null,
    aiReviewNotes: null,
    resultSentToUserApp: false,
  },
  {
    orderId: 'LAB1023',
    patientName: 'Sunrise Clinic',
    patientPhone: '+95 1 500 600',
    testType: 'COVID PCR',
    orderDate: '2026-04-22',
    status: 'completed',
    paymentStatus: 'paid',
    technician: 'Hnin Wai',
    source: 'clinic_portal',
    patientAddress: 'Industrial Zone 4, Hlaing Tharyar, Yangon',
    amountMmk: 95_000,
    collectionTime: '2026-04-22T08:00',
    collectingPerson: 'Ko Htoo',
    labRunningCompleteAt: '2026-04-22T16:00',
    reportOutTime: '2026-04-23T08:00',
    resultPdfFileName: 'LAB1023_report.pdf',
    aiReviewPassed: true,
    aiReviewNotes: 'Values within expected QC bands (demo).',
    resultSentToUserApp: true,
  },
  {
    orderId: 'LAB1024',
    patientName: 'Dr. Aung',
    patientPhone: '+95 9 777 888 999',
    testType: 'Liver Function Test',
    orderDate: '2026-04-21',
    status: 'pending',
    paymentStatus: 'unpaid',
    technician: undefined,
    source: 'doctor_app',
    patientAddress: '78 University Avenue, Kamayut, Yangon',
    amountMmk: 150_000,
    collectionTime: '2026-04-27T11:00',
    collectingPerson: 'Unassigned',
    labRunningCompleteAt: '2026-04-27T19:00',
    reportOutTime: '2026-04-28T09:00',
    resultPdfFileName: null,
    aiReviewPassed: null,
    aiReviewNotes: null,
    resultSentToUserApp: false,
  },
]

/** Static snapshot for charts / tables that do not use live context (optional). */
export const orders = INITIAL_ORDERS
