/** Image URLs from Stitch (MedLab Smart ) mockups — same assets as `modern_login_screen`. */

export const authImages = {
  loginHero:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuBoK7GDLlxKfvwoJezYSjqaiTHmIxdOZisNxpOqM3LWIgiUhEPT5jN5X8GPnwuiVfSaj3oBF9Ls6ku3ppLEpNWBRwcXI40b8sqCPynJEwQpuYdw-muxuPGfng0xouWU26yRwk7ILREO_ZFL2Vj2wD0J025zfi9-SvihA0XamLnjcfRXcK7PuJOrIRVhtxazrRWbMvY7y-sxfLCX-dfr1jBnh6P6UdprvjLxtWEu-Q5ClgTwyqbEwoCvaN9vpuNpC0pRsbd3EoCChJg',
  iso: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDwUCq81gPRmSlIstbB7COSz2NjrPhRPNswN3dFAFq9nZ2UhYkAFRPYDf1dV1vIAgmOG6ugWjhoM0Y45U_yj_dObAnhEniHQHqNDKN4LI466b-FBNh8ADNMo9RBzULIATXOKrxpHaUjAjRm0GDqwTsO0aWx6muwqet3rHgVHMVLaV_orM_ZFcnkEDrgexY61lfQuPFZd6gYZcko7YoNPbDiYIf-BiPOdv3vuiTTYF3nV41eGQeRCqdwYcT9f1_o8-Z0ZRnNqKQT77E',
  hipaa:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuAlpiwCk2BLlS-000ng3A3zkq9Ta87Dgo_Yqfxh5wSVear-b1gTGlKSCCCUJ7tDVtVZ620zG7c_rbu1lRuKbbuaWIVsSQh8_TYZ1uAspx641I-tz6Es5VCvQ16X0Sjq3ePkHnD_kYTZmuWjfjlYdP4cMTtZuicL_ZSYLPgjEDpGvD0CYAmgjyLjL0QlAHRi8GFctTAH06Kr3QBXabe_ykiscMNBtDHBSvhLymBmQ92aFm-YLZsQJKsAhceNQVPn1APiQOH_cdqvEvM',
} as const
